// SPDX-License-Identifier: AGPL-3.0-or-later
//
// dnsmasq lifecycle for the .test TLD. Runs unprivileged on port 5353
// because `/etc/resolver/test` opts the macOS resolver into a custom
// port, so we never need to bind 53.

use std::path::PathBuf;

use crate::domain::process::{ProcessSpec, ProcessSupervisor};
use crate::error::{ForgeError, ForgeResult};
use crate::store;

pub const DNSMASQ_PROCESS: &str = "dnsmasq";
pub const DNSMASQ_PORT: u16 = 5353;

fn runtime_dir() -> PathBuf {
    store::data_dir().join("runtime").join("dnsmasq")
}

fn config_path() -> PathBuf {
    runtime_dir().join("dnsmasq.conf")
}

fn pid_path() -> PathBuf {
    runtime_dir().join("dnsmasq.pid")
}

pub fn render_config() -> ForgeResult<PathBuf> {
    let dir = runtime_dir();
    std::fs::create_dir_all(&dir)
        .map_err(|e| ForgeError::Other(format!("create dnsmasq runtime dir: {e}")))?;

    let config = format!(
        "# Generated by Delify Forge — do not edit by hand.\n\
         port={port}\n\
         no-daemon\n\
         no-hosts\n\
         no-resolv\n\
         bind-interfaces\n\
         listen-address=127.0.0.1\n\
         address=/.test/127.0.0.1\n\
         pid-file={pid}\n\
         log-queries=no\n",
        port = DNSMASQ_PORT,
        pid = pid_path().display()
    );

    let path = config_path();
    std::fs::write(&path, config)
        .map_err(|e| ForgeError::Other(format!("write dnsmasq.conf: {e}")))?;
    Ok(path)
}

pub async fn start(supervisor: &ProcessSupervisor) -> ForgeResult<u32> {
    let binary =
        crate::platform::macos::detect_binary("dnsmasq", &["--version"]).ok_or_else(|| {
            ForgeError::Other("dnsmasq not found — install with: brew install dnsmasq".into())
        })?;

    let config = render_config()?;

    let spec = ProcessSpec {
        name: DNSMASQ_PROCESS.to_string(),
        binary: binary.binary,
        args: vec![
            "--keep-in-foreground".to_string(),
            "--conf-file".to_string(),
            config.to_string_lossy().to_string(),
        ],
        env: Vec::new(),
    };

    supervisor.start(spec).await
}

pub async fn stop(supervisor: &ProcessSupervisor) -> ForgeResult<()> {
    supervisor.stop(DNSMASQ_PROCESS).await
}
